-- SQL Queries für einfache Rezepte nach Ernährungskategorien
-- Kombiniert Rezepte mit weniger als 5 Zutaten mit spezifischen Ernährungsweisen

-- 1. Einfache vegane Rezepte (< 5 Zutaten)
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(DISTINCT e.ERNAEHRUNGSKATEGORIENAME SEPARATOR ', ') as KATEGORIEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
INNER JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
WHERE e.ERNAEHRUNGSKATEGORIENAME = 'Vegan'
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 5
ORDER BY ANZAHL_ZUTATEN, r.ZUBEREITUNGSZEIT;

-- 2. Einfache vegetarische Rezepte (< 5 Zutaten)
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(DISTINCT e.ERNAEHRUNGSKATEGORIENAME SEPARATOR ', ') as KATEGORIEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
INNER JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
WHERE e.ERNAEHRUNGSKATEGORIENAME = 'Vegetarisch'
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 5
ORDER BY ANZAHL_ZUTATEN, r.ZUBEREITUNGSZEIT;

-- 3. Einfache Low-Carb Rezepte (< 5 Zutaten)
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(DISTINCT e.ERNAEHRUNGSKATEGORIENAME SEPARATOR ', ') as KATEGORIEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
INNER JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
WHERE e.ERNAEHRUNGSKATEGORIENAME = 'Low Carb'
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 5
ORDER BY ANZAHL_ZUTATEN, r.ZUBEREITUNGSZEIT;

-- 4. Parametrisierte Version: Einfache Rezepte für BELIEBIGE Ernährungskategorie
-- Ersetze 'Vegan' durch gewünschte Kategorie: 'Vegetarisch', 'Keto', 'Low Carb', 'Pescetarier'
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(DISTINCT z.BEZEICHNUNG SEPARATOR ', ') as ZUTATEN_LISTE,
    GROUP_CONCAT(DISTINCT e.ERNAEHRUNGSKATEGORIENAME SEPARATOR ', ') as KATEGORIEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
LEFT JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
INNER JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
WHERE e.ERNAEHRUNGSKATEGORIENAME = 'Vegan'  -- HIER KATEGORIE ÄNDERN
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 5
ORDER BY ANZAHL_ZUTATEN, r.ZUBEREITUNGSZEIT;

-- 5. Übersicht: Einfache Rezepte ALLER Ernährungskategorien
SELECT 
    e.ERNAEHRUNGSKATEGORIENAME,
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
INNER JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
GROUP BY e.ERNAEHRUNGSKATEGORIENAME, r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 5
ORDER BY e.ERNAEHRUNGSKATEGORIENAME, ANZAHL_ZUTATEN, r.ZUBEREITUNGSZEIT;

-- 6. Statistik: Anzahl einfacher Rezepte pro Ernährungskategorie
SELECT 
    e.ERNAEHRUNGSKATEGORIENAME,
    COUNT(DISTINCT r.REZEPTNR) as ANZAHL_EINFACHER_REZEPTE,
    AVG(zutat_count.ANZAHL_ZUTATEN) as AVG_ZUTATEN,
    MIN(r.ZUBEREITUNGSZEIT) as MIN_ZUBEREITUNGSZEIT,
    AVG(r.ZUBEREITUNGSZEIT) as AVG_ZUBEREITUNGSZEIT,
    MAX(r.ZUBEREITUNGSZEIT) as MAX_ZUBEREITUNGSZEIT
FROM ERNAEHRUNGSKATEGORIE e
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON e.ERNAEHRUNGSKATEGORIENR = rek.ERNAEHRUNGSKATEGORIENR
INNER JOIN REZEPT r ON rek.REZEPTNR = r.REZEPTNR
INNER JOIN (
    SELECT 
        rezept_inner.REZEPTNR,
        COUNT(rz_inner.ZUTATENNR) as ANZAHL_ZUTATEN
    FROM REZEPT rezept_inner
    LEFT JOIN REZEPTZUTAT rz_inner ON rezept_inner.REZEPTNR = rz_inner.REZEPTNR
    GROUP BY rezept_inner.REZEPTNR
    HAVING COUNT(rz_inner.ZUTATENNR) < 5
) zutat_count ON r.REZEPTNR = zutat_count.REZEPTNR
GROUP BY e.ERNAEHRUNGSKATEGORIENAME
ORDER BY ANZAHL_EINFACHER_REZEPTE DESC;

-- 7. Detailversion mit Zutat-Mengen für spezifische Kategorie
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(
        DISTINCT CONCAT(z.BEZEICHNUNG, ' (', rz.MENGE, ' ', rz.EINHEIT, ')')
        ORDER BY z.BEZEICHNUNG
        SEPARATOR ', '
    ) as ZUTATEN_MIT_MENGEN,
    GROUP_CONCAT(DISTINCT e.ERNAEHRUNGSKATEGORIENAME SEPARATOR ', ') as KATEGORIEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
LEFT JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
INNER JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
WHERE e.ERNAEHRUNGSKATEGORIENAME = 'Vegetarisch'  -- HIER KATEGORIE ÄNDERN
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 5
ORDER BY ANZAHL_ZUTATEN, r.ZUBEREITUNGSZEIT;

-- 8. Schnellste einfache Rezepte nach Kategorie (unter 30 Minuten)
SELECT 
    e.ERNAEHRUNGSKATEGORIENAME,
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(DISTINCT z.BEZEICHNUNG ORDER BY z.BEZEICHNUNG SEPARATOR ', ') as ZUTATEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
LEFT JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
INNER JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
INNER JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
WHERE r.ZUBEREITUNGSZEIT <= 30
GROUP BY e.ERNAEHRUNGSKATEGORIENAME, r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 5
ORDER BY e.ERNAEHRUNGSKATEGORIENAME, r.ZUBEREITUNGSZEIT, ANZAHL_ZUTATEN;