-- SQL Queries für kalorienarme Rezepte
-- Diese Queries helfen beim Finden von Rezepten mit bestimmten Kaloriengrenzen

-- 1. Einfache Version: Rezepte unter bestimmter Kalorienmenge (z.B. 100 kcal)
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN <= 100
ORDER BY GESAMT_KALORIEN, r.REZEPTNAME;

-- 2. Detailliert: Mit Kalorien-Aufschlüsselung pro Zutat
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(
        CONCAT(z.BEZEICHNUNG, ' (', COALESCE(z.KALORIEN, 0), ' kcal)')
        ORDER BY z.KALORIEN DESC SEPARATOR ', '
    ) as KALORIEN_AUFSCHLÜSSELUNG
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN <= 80  -- Sehr kalorienarm
ORDER BY GESAMT_KALORIEN, r.REZEPTNAME;

-- 3. Kategorisierte Kalorien-Bereiche
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    CASE 
        WHEN SUM(COALESCE(z.KALORIEN, 0)) <= 50 THEN 'SEHR KALORIENARM'
        WHEN SUM(COALESCE(z.KALORIEN, 0)) <= 100 THEN 'KALORIENARM'
        WHEN SUM(COALESCE(z.KALORIEN, 0)) <= 200 THEN 'MITTEL'
        WHEN SUM(COALESCE(z.KALORIEN, 0)) <= 300 THEN 'NORMAL'
        ELSE 'KALORIENREICH'
    END as KALORIEN_KATEGORIE
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
ORDER BY GESAMT_KALORIEN, r.REZEPTNAME;

-- 4. Flexible Query mit Parameter (Kaloriengrenze anpassbar)
-- Ersetze die Zahl 150 mit gewünschter Kaloriengrenze
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    ROUND(SUM(COALESCE(z.KALORIEN, 0)) / COUNT(DISTINCT rz.ZUTATENNR), 2) as DURCHSCHNITT_PRO_ZUTAT,
    GROUP_CONCAT(DISTINCT z.BEZEICHNUNG ORDER BY z.BEZEICHNUNG SEPARATOR ', ') as ZUTATEN
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN <= 150  -- PARAMETER: Hier Kaloriengrenze anpassen
ORDER BY GESAMT_KALORIEN;

-- 5. Ultra-kalorienarm: Nur Rezepte unter 50 kcal
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(
        CONCAT(z.BEZEICHNUNG, ': ', COALESCE(z.KALORIEN, 0), ' kcal')
        ORDER BY z.BEZEICHNUNG SEPARATOR ' | '
    ) as DETAILLIERTE_KALORIEN
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN <= 50
ORDER BY GESAMT_KALORIEN, r.ZUBEREITUNGSZEIT;

-- 6. Kalorienarm UND einfach: Weniger als 100 kcal UND weniger als 4 Zutaten
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    'KALORIENARM + EINFACH' as KATEGORIE,
    GROUP_CONCAT(DISTINCT z.BEZEICHNUNG ORDER BY z.BEZEICHNUNG SEPARATOR ', ') as ZUTATEN
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN <= 100 AND COUNT(DISTINCT rz.ZUTATENNR) < 4
ORDER BY GESAMT_KALORIEN, ANZAHL_ZUTATEN;

-- 7. Kalorien-Effizienz: Niedrigste Kalorien pro Zutat
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    ROUND(SUM(COALESCE(z.KALORIEN, 0)) / COUNT(DISTINCT rz.ZUTATENNR), 2) as KALORIEN_PRO_ZUTAT
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN > 0
ORDER BY KALORIEN_PRO_ZUTAT, GESAMT_KALORIEN
LIMIT 10;

-- 8. Kalorienarm + Schnell: Unter 80 kcal UND unter 30 Min Zubereitung
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    'KALORIENARM + SCHNELL' as KATEGORIE
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
WHERE r.ZUBEREITUNGSZEIT <= 30
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN <= 80
ORDER BY GESAMT_KALORIEN, r.ZUBEREITUNGSZEIT;

-- 9. Statistik: Kalorien-Verteilung aller Rezepte
SELECT 
    'SEHR KALORIENARM (≤50)' as KATEGORIE,
    COUNT(*) as ANZAHL_REZEPTE,
    ROUND(AVG(kalorien_summe), 2) as DURCHSCHNITT_KALORIEN
FROM (
    SELECT r.REZEPTNR, SUM(COALESCE(z.KALORIEN, 0)) as kalorien_summe
    FROM REZEPT r
    INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
    INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
    GROUP BY r.REZEPTNR
    HAVING kalorien_summe <= 50
) as sehr_kalorienarm

UNION ALL

SELECT 
    'KALORIENARM (51-100)' as KATEGORIE,
    COUNT(*) as ANZAHL_REZEPTE,
    ROUND(AVG(kalorien_summe), 2) as DURCHSCHNITT_KALORIEN
FROM (
    SELECT r.REZEPTNR, SUM(COALESCE(z.KALORIEN, 0)) as kalorien_summe
    FROM REZEPT r
    INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
    INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
    GROUP BY r.REZEPTNR
    HAVING kalorien_summe > 50 AND kalorien_summe <= 100
) as kalorienarm

UNION ALL

SELECT 
    'NORMAL (101-200)' as KATEGORIE,
    COUNT(*) as ANZAHL_REZEPTE,
    ROUND(AVG(kalorien_summe), 2) as DURCHSCHNITT_KALORIEN
FROM (
    SELECT r.REZEPTNR, SUM(COALESCE(z.KALORIEN, 0)) as kalorien_summe
    FROM REZEPT r
    INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
    INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
    GROUP BY r.REZEPTNR
    HAVING kalorien_summe > 100 AND kalorien_summe <= 200
) as normal;

-- 10. Erweitert: Mit Ernährungskategorien und Kalorien
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.ZUBEREITUNGSZEIT,
    SUM(COALESCE(z.KALORIEN, 0)) as GESAMT_KALORIEN,
    COUNT(DISTINCT rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(DISTINCT e.ERNAEHRUNGSKATEGORIENAME SEPARATOR ', ') as ERNÄHRUNGSKATEGORIEN
FROM REZEPT r
INNER JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
INNER JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
LEFT JOIN REZEPTERNAEHRUNGSKATEGORIE rek ON r.REZEPTNR = rek.REZEPTNR
LEFT JOIN ERNAEHRUNGSKATEGORIE e ON rek.ERNAEHRUNGSKATEGORIENR = e.ERNAEHRUNGSKATEGORIENR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.ZUBEREITUNGSZEIT
HAVING GESAMT_KALORIEN <= 100
ORDER BY GESAMT_KALORIEN, r.REZEPTNAME;