-- SQL Queries für Nährwerte-Analysen pro Bestellung
-- Berechnung durchschnittlicher Nährwerte pro Kunde und Bestellung

-- ============================================================================
-- 1. Nährwerte pro einzelne Bestellung
-- ============================================================================

-- 1a) Basis-Query: Nährwerte pro Bestellung mit Kundendaten
SELECT 
    b.BESTELLNR,
    b.KUNDENNR,
    CONCAT(k.VORNAME, ' ', k.NACHNAME) as KUNDE_NAME,
    b.BESTELLDATUM,
    b.RECHNUNGSBETRAG,
    SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) as GESAMT_KALORIEN,
    SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) as GESAMT_PROTEIN_G,
    SUM(COALESCE(z.KOHLENHYDRATE, 0) * bz.MENGE) as GESAMT_KOHLENHYDRATE_G,
    COUNT(DISTINCT bz.ZUTATENNR) as ANZAHL_VERSCHIEDENE_ZUTATEN,
    SUM(bz.MENGE) as GESAMT_MENGE_EINHEITEN
FROM BESTELLUNG b
INNER JOIN KUNDE k ON b.KUNDENNR = k.KUNDENNR
INNER JOIN BESTELLUNGZUTAT bz ON b.BESTELLNR = bz.BESTELLNR
INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
GROUP BY b.BESTELLNR, b.KUNDENNR, k.VORNAME, k.NACHNAME, b.BESTELLDATUM, b.RECHNUNGSBETRAG
ORDER BY b.BESTELLDATUM DESC;

-- 1b) Erweiterte Nährwerte-Analyse pro Bestellung
SELECT 
    b.BESTELLNR,
    CONCAT(k.VORNAME, ' ', k.NACHNAME) as KUNDE_NAME,
    b.BESTELLDATUM,
    SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) as GESAMT_KALORIEN,
    SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) as GESAMT_PROTEIN_G,
    SUM(COALESCE(z.KOHLENHYDRATE, 0) * bz.MENGE) as GESAMT_KOHLENHYDRATE_G,
    ROUND(SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) / SUM(bz.MENGE), 2) as KALORIEN_PRO_EINHEIT,
    ROUND(SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) / SUM(bz.MENGE), 2) as PROTEIN_PRO_EINHEIT,
    ROUND(SUM(COALESCE(z.KOHLENHYDRATE, 0) * bz.MENGE) / SUM(bz.MENGE), 2) as KOHLENHYDRATE_PRO_EINHEIT,
    COUNT(DISTINCT bz.ZUTATENNR) as ANZAHL_ZUTATEN,
    SUM(bz.MENGE) as GESAMT_MENGE
FROM BESTELLUNG b
INNER JOIN KUNDE k ON b.KUNDENNR = k.KUNDENNR
INNER JOIN BESTELLUNGZUTAT bz ON b.BESTELLNR = bz.BESTELLNR
INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
GROUP BY b.BESTELLNR, k.VORNAME, k.NACHNAME, b.BESTELLDATUM
ORDER BY GESAMT_KALORIEN DESC;

-- ============================================================================
-- 2. DURCHSCHNITTLICHE NÄHRWERTE PRO KUNDE (Hauptfrage)
-- ============================================================================

-- 2a) Durchschnittliche Nährwerte pro Bestellung für alle Kunden
SELECT 
    k.KUNDENNR,
    CONCAT(k.VORNAME, ' ', k.NACHNAME) as KUNDE_NAME,
    k.EMAIL,
    COUNT(DISTINCT b.BESTELLNR) as ANZAHL_BESTELLUNGEN,
    -- Durchschnittliche Nährwerte pro Bestellung
    ROUND(AVG(bestellung_naehrwerte.KALORIEN_PRO_BESTELLUNG), 2) as AVG_KALORIEN_PRO_BESTELLUNG,
    ROUND(AVG(bestellung_naehrwerte.PROTEIN_PRO_BESTELLUNG), 2) as AVG_PROTEIN_PRO_BESTELLUNG,
    ROUND(AVG(bestellung_naehrwerte.KOHLENHYDRATE_PRO_BESTELLUNG), 2) as AVG_KOHLENHYDRATE_PRO_BESTELLUNG,
    -- Gesamte Nährwerte über alle Bestellungen
    SUM(bestellung_naehrwerte.KALORIEN_PRO_BESTELLUNG) as GESAMT_KALORIEN_ALLE_BESTELLUNGEN,
    SUM(bestellung_naehrwerte.PROTEIN_PRO_BESTELLUNG) as GESAMT_PROTEIN_ALLE_BESTELLUNGEN,
    SUM(bestellung_naehrwerte.KOHLENHYDRATE_PRO_BESTELLUNG) as GESAMT_KOHLENHYDRATE_ALLE_BESTELLUNGEN,
    -- Zusätzliche Statistiken
    ROUND(AVG(bestellung_naehrwerte.ANZAHL_ZUTATEN), 2) as AVG_ZUTATEN_PRO_BESTELLUNG,
    SUM(b.RECHNUNGSBETRAG) as GESAMT_UMSATZ
FROM KUNDE k
INNER JOIN BESTELLUNG b ON k.KUNDENNR = b.KUNDENNR
INNER JOIN (
    -- Subselect: Nährwerte pro Bestellung berechnen
    SELECT 
        b_inner.BESTELLNR,
        b_inner.KUNDENNR,
        SUM(COALESCE(z_inner.KALORIEN, 0) * bz_inner.MENGE) as KALORIEN_PRO_BESTELLUNG,
        SUM(COALESCE(z_inner.PROTEIN, 0) * bz_inner.MENGE) as PROTEIN_PRO_BESTELLUNG,
        SUM(COALESCE(z_inner.KOHLENHYDRATE, 0) * bz_inner.MENGE) as KOHLENHYDRATE_PRO_BESTELLUNG,
        COUNT(DISTINCT bz_inner.ZUTATENNR) as ANZAHL_ZUTATEN
    FROM BESTELLUNG b_inner
    INNER JOIN BESTELLUNGZUTAT bz_inner ON b_inner.BESTELLNR = bz_inner.BESTELLNR
    INNER JOIN ZUTAT z_inner ON bz_inner.ZUTATENNR = z_inner.ZUTATENNR
    GROUP BY b_inner.BESTELLNR, b_inner.KUNDENNR
) as bestellung_naehrwerte ON b.BESTELLNR = bestellung_naehrwerte.BESTELLNR
GROUP BY k.KUNDENNR, k.VORNAME, k.NACHNAME, k.EMAIL
HAVING COUNT(DISTINCT b.BESTELLNR) > 0  -- Nur Kunden mit Bestellungen
ORDER BY AVG_KALORIEN_PRO_BESTELLUNG DESC;

-- 2b) Vereinfachte Version: Durchschnittliche Nährwerte pro Kunde
SELECT 
    k.KUNDENNR,
    CONCAT(k.VORNAME, ' ', k.NACHNAME) as KUNDE_NAME,
    COUNT(DISTINCT b.BESTELLNR) as ANZAHL_BESTELLUNGEN,
    ROUND(SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR), 2) as AVG_KALORIEN_PRO_BESTELLUNG,
    ROUND(SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR), 2) as AVG_PROTEIN_PRO_BESTELLUNG,
    ROUND(SUM(COALESCE(z.KOHLENHYDRATE, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR), 2) as AVG_KOHLENHYDRATE_PRO_BESTELLUNG
FROM KUNDE k
INNER JOIN BESTELLUNG b ON k.KUNDENNR = b.KUNDENNR
INNER JOIN BESTELLUNGZUTAT bz ON b.BESTELLNR = bz.BESTELLNR
INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
GROUP BY k.KUNDENNR, k.VORNAME, k.NACHNAME
ORDER BY AVG_KALORIEN_PRO_BESTELLUNG DESC;

-- ============================================================================
-- 3. Spezielle Analysen und Filter
-- ============================================================================

-- 3a) Top-Kunden nach Nährwert-Kategorien
SELECT 
    'HÖCHSTE KALORIEN' as KATEGORIE,
    CONCAT(k.VORNAME, ' ', k.NACHNAME) as KUNDE_NAME,
    ROUND(SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR), 2) as AVG_WERT_PRO_BESTELLUNG,
    COUNT(DISTINCT b.BESTELLNR) as ANZAHL_BESTELLUNGEN
FROM KUNDE k
INNER JOIN BESTELLUNG b ON k.KUNDENNR = b.KUNDENNR
INNER JOIN BESTELLUNGZUTAT bz ON b.BESTELLNR = bz.BESTELLNR
INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
GROUP BY k.KUNDENNR, k.VORNAME, k.NACHNAME
ORDER BY AVG_WERT_PRO_BESTELLUNG DESC
LIMIT 5

UNION ALL

SELECT 
    'HÖCHSTES PROTEIN' as KATEGORIE,
    CONCAT(k.VORNAME, ' ', k.NACHNAME) as KUNDE_NAME,
    ROUND(SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR), 2) as AVG_WERT_PRO_BESTELLUNG,
    COUNT(DISTINCT b.BESTELLNR) as ANZAHL_BESTELLUNGEN
FROM KUNDE k
INNER JOIN BESTELLUNG b ON k.KUNDENNR = b.KUNDENNR
INNER JOIN BESTELLUNGZUTAT bz ON b.BESTELLNR = bz.BESTELLNR
INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
GROUP BY k.KUNDENNR, k.VORNAME, k.NACHNAME
ORDER BY AVG_WERT_PRO_BESTELLUNG DESC
LIMIT 5;

-- 3b) Kunden mit gesunden vs. ungesunden Bestellmustern
SELECT 
    k.KUNDENNR,
    CONCAT(k.VORNAME, ' ', k.NACHNAME) as KUNDE_NAME,
    COUNT(DISTINCT b.BESTELLNR) as ANZAHL_BESTELLUNGEN,
    ROUND(SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR), 2) as AVG_KALORIEN,
    ROUND(SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR), 2) as AVG_PROTEIN,
    CASE 
        WHEN SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR) <= 50 THEN 'KALORIENARM'
        WHEN SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR) <= 100 THEN 'NORMAL'
        ELSE 'KALORIENREICH'
    END as KALORIEN_KATEGORIE,
    CASE 
        WHEN SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR) >= 5 THEN 'PROTEINREICH'
        WHEN SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) / COUNT(DISTINCT b.BESTELLNR) >= 2 THEN 'NORMAL'
        ELSE 'PROTEINARM'
    END as PROTEIN_KATEGORIE
FROM KUNDE k
INNER JOIN BESTELLUNG b ON k.KUNDENNR = b.KUNDENNR
INNER JOIN BESTELLUNGZUTAT bz ON b.BESTELLNR = bz.BESTELLNR
INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
GROUP BY k.KUNDENNR, k.VORNAME, k.NACHNAME
ORDER BY AVG_KALORIEN DESC;

-- ============================================================================
-- 4. Zeitbasierte Nährwerte-Analysen
-- ============================================================================

-- 4a) Nährwerte-Trends nach Monaten
SELECT 
    YEAR(b.BESTELLDATUM) as JAHR,
    MONTH(b.BESTELLDATUM) as MONAT,
    MONTHNAME(b.BESTELLDATUM) as MONATSNAME,
    COUNT(DISTINCT b.BESTELLNR) as ANZAHL_BESTELLUNGEN,
    COUNT(DISTINCT b.KUNDENNR) as ANZAHL_VERSCHIEDENE_KUNDEN,
    ROUND(AVG(naehrwerte_pro_bestellung.KALORIEN), 2) as AVG_KALORIEN_PRO_BESTELLUNG,
    ROUND(AVG(naehrwerte_pro_bestellung.PROTEIN), 2) as AVG_PROTEIN_PRO_BESTELLUNG,
    ROUND(AVG(naehrwerte_pro_bestellung.KOHLENHYDRATE), 2) as AVG_KOHLENHYDRATE_PRO_BESTELLUNG
FROM BESTELLUNG b
INNER JOIN (
    SELECT 
        b_inner.BESTELLNR,
        SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) as KALORIEN,
        SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) as PROTEIN,
        SUM(COALESCE(z.KOHLENHYDRATE, 0) * bz.MENGE) as KOHLENHYDRATE
    FROM BESTELLUNG b_inner
    INNER JOIN BESTELLUNGZUTAT bz ON b_inner.BESTELLNR = bz.BESTELLNR
    INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
    GROUP BY b_inner.BESTELLNR
) as naehrwerte_pro_bestellung ON b.BESTELLNR = naehrwerte_pro_bestellung.BESTELLNR
GROUP BY YEAR(b.BESTELLDATUM), MONTH(b.BESTELLDATUM), MONTHNAME(b.BESTELLDATUM)
ORDER BY JAHR, MONAT;

-- ============================================================================
-- 5. Vergleichsanalysen und Statistiken
-- ============================================================================

-- 5a) Gesamtstatistik: Durchschnittswerte aller Kunden
SELECT 
    'SYSTEM-DURCHSCHNITT' as KATEGORIE,
    COUNT(DISTINCT k.KUNDENNR) as ANZAHL_KUNDEN,
    COUNT(DISTINCT b.BESTELLNR) as ANZAHL_BESTELLUNGEN,
    ROUND(AVG(bestellung_stats.AVG_KALORIEN), 2) as SYSTEM_AVG_KALORIEN,
    ROUND(AVG(bestellung_stats.AVG_PROTEIN), 2) as SYSTEM_AVG_PROTEIN,
    ROUND(AVG(bestellung_stats.AVG_KOHLENHYDRATE), 2) as SYSTEM_AVG_KOHLENHYDRATE,
    MIN(bestellung_stats.AVG_KALORIEN) as MIN_KALORIEN_PRO_KUNDE,
    MAX(bestellung_stats.AVG_KALORIEN) as MAX_KALORIEN_PRO_KUNDE
FROM KUNDE k
INNER JOIN BESTELLUNG b ON k.KUNDENNR = b.KUNDENNR
INNER JOIN (
    SELECT 
        kunde_inner.KUNDENNR,
        SUM(COALESCE(z.KALORIEN, 0) * bz.MENGE) / COUNT(DISTINCT b_inner.BESTELLNR) as AVG_KALORIEN,
        SUM(COALESCE(z.PROTEIN, 0) * bz.MENGE) / COUNT(DISTINCT b_inner.BESTELLNR) as AVG_PROTEIN,
        SUM(COALESCE(z.KOHLENHYDRATE, 0) * bz.MENGE) / COUNT(DISTINCT b_inner.BESTELLNR) as AVG_KOHLENHYDRATE
    FROM KUNDE kunde_inner
    INNER JOIN BESTELLUNG b_inner ON kunde_inner.KUNDENNR = b_inner.KUNDENNR
    INNER JOIN BESTELLUNGZUTAT bz ON b_inner.BESTELLNR = bz.BESTELLNR
    INNER JOIN ZUTAT z ON bz.ZUTATENNR = z.ZUTATENNR
    GROUP BY kunde_inner.KUNDENNR
) as bestellung_stats ON k.KUNDENNR = bestellung_stats.KUNDENNR;