-- SQL Queries für Rezepte mit weniger als 3 Zutaten

-- 1. Einfache Version: Rezepte mit weniger als 3 Zutaten
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 3
ORDER BY ANZAHL_ZUTATEN, r.REZEPTNAME;

-- 2. Detaillierte Version: Mit Zutatenliste
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(z.BEZEICHNUNG SEPARATOR ', ') as ZUTATEN_LISTE
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
LEFT JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 3
ORDER BY ANZAHL_ZUTATEN, r.REZEPTNAME;

-- 3. Mit Mengenangaben: Inklusive Zutat-Mengen
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    COUNT(rz.ZUTATENNR) as ANZAHL_ZUTATEN,
    GROUP_CONCAT(
        CONCAT(z.BEZEICHNUNG, ' (', rz.MENGE, ' ', rz.EINHEIT, ')') 
        SEPARATOR ', '
    ) as ZUTATEN_MIT_MENGE
FROM REZEPT r
LEFT JOIN REZEPTZUTAT rz ON r.REZEPTNR = rz.REZEPTNR
LEFT JOIN ZUTAT z ON rz.ZUTATENNR = z.ZUTATENNR
GROUP BY r.REZEPTNR, r.REZEPTNAME, r.BESCHREIBUNG, r.ZUBEREITUNGSZEIT
HAVING COUNT(rz.ZUTATENNR) < 3
ORDER BY ANZAHL_ZUTATEN, r.REZEPTNAME;

-- 4. Subquery Version (Alternative Implementierung)
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT
FROM REZEPT r
WHERE r.REZEPTNR IN (
    SELECT rz.REZEPTNR
    FROM REZEPTZUTAT rz
    GROUP BY rz.REZEPTNR
    HAVING COUNT(rz.ZUTATENNR) < 3
)
ORDER BY r.REZEPTNAME;

-- 5. Performance-optimierte Version mit EXISTS
SELECT 
    r.REZEPTNR,
    r.REZEPTNAME,
    r.BESCHREIBUNG,
    r.ZUBEREITUNGSZEIT,
    (SELECT COUNT(*) FROM REZEPTZUTAT rz WHERE rz.REZEPTNR = r.REZEPTNR) as ANZAHL_ZUTATEN
FROM REZEPT r
WHERE (SELECT COUNT(*) FROM REZEPTZUTAT rz WHERE rz.REZEPTNR = r.REZEPTNR) < 3
ORDER BY ANZAHL_ZUTATEN, r.REZEPTNAME;