-- SQL Queries für ungenutzte Zutaten
-- Diese Queries identifizieren Zutaten, die bisher keinem Rezept zugeordnet sind

-- 1. Einfache Version: Alle ungenutzten Zutaten
SELECT 
    z.ZUTATENNR,
    z.BEZEICHNUNG,
    z.EINHEIT,
    z.NETTOPREIS,
    z.BESTAND,
    z.KALORIEN
FROM ZUTAT z
LEFT JOIN REZEPTZUTAT rz ON z.ZUTATENNR = rz.ZUTATENNR
WHERE rz.ZUTATENNR IS NULL
ORDER BY z.BEZEICHNUNG;

-- 2. Mit Lieferanten-Information
SELECT 
    z.ZUTATENNR,
    z.BEZEICHNUNG,
    z.EINHEIT,
    z.NETTOPREIS,
    z.BESTAND,
    z.KALORIEN,
    l.LIEFERANTENNAME as LIEFERANT
FROM ZUTAT z
LEFT JOIN REZEPTZUTAT rz ON z.ZUTATENNR = rz.ZUTATENNR
LEFT JOIN LIEFERANT l ON z.LIEFERANTENNR = l.LIEFERANTENNR
WHERE rz.ZUTATENNR IS NULL
ORDER BY l.LIEFERANTENNAME, z.BEZEICHNUNG;

-- 3. Mit Bestandswert-Analyse (potenzielle Kosteneinsparung)
SELECT 
    z.ZUTATENNR,
    z.BEZEICHNUNG,
    z.EINHEIT,
    z.BESTAND,
    z.NETTOPREIS,
    ROUND(z.BESTAND * z.NETTOPREIS, 2) as BESTANDSWERT,
    z.KALORIEN
FROM ZUTAT z
LEFT JOIN REZEPTZUTAT rz ON z.ZUTATENNR = rz.ZUTATENNR
WHERE rz.ZUTATENNR IS NULL
ORDER BY BESTANDSWERT DESC;

-- 4. Zusammenfassung: Anzahl und Gesamtwert ungenutzter Zutaten
SELECT 
    COUNT(*) as ANZAHL_UNGENUTZTE_ZUTATEN,
    SUM(z.BESTAND) as GESAMT_BESTAND_EINHEITEN,
    ROUND(SUM(z.BESTAND * z.NETTOPREIS), 2) as GESAMTWERT_UNGENUTZT
FROM ZUTAT z
LEFT JOIN REZEPTZUTAT rz ON z.ZUTATENNR = rz.ZUTATENNR
WHERE rz.ZUTATENNR IS NULL;

-- 5. Gegencheck: Zutaten die VERWENDET werden
SELECT 
    z.ZUTATENNR,
    z.BEZEICHNUNG,
    COUNT(DISTINCT rz.REZEPTNR) as VERWENDUNG_IN_REZEPTEN,
    GROUP_CONCAT(DISTINCT r.REZEPTNAME SEPARATOR ', ') as REZEPTE
FROM ZUTAT z
INNER JOIN REZEPTZUTAT rz ON z.ZUTATENNR = rz.ZUTATENNR
INNER JOIN REZEPT r ON rz.REZEPTNR = r.REZEPTNR
GROUP BY z.ZUTATENNR, z.BEZEICHNUNG
ORDER BY VERWENDUNG_IN_REZEPTEN DESC, z.BEZEICHNUNG;

-- 6. Detailanalyse: Alle Zutaten mit Verwendungsstatus
SELECT 
    z.ZUTATENNR,
    z.BEZEICHNUNG,
    z.EINHEIT,
    z.BESTAND,
    z.NETTOPREIS,
    CASE 
        WHEN rz.ZUTATENNR IS NULL THEN 'UNGENUTZT'
        ELSE 'VERWENDET'
    END as STATUS,
    COALESCE(COUNT(DISTINCT rz.REZEPTNR), 0) as ANZAHL_REZEPTE
FROM ZUTAT z
LEFT JOIN REZEPTZUTAT rz ON z.ZUTATENNR = rz.ZUTATENNR
GROUP BY z.ZUTATENNR, z.BEZEICHNUNG, z.EINHEIT, z.BESTAND, z.NETTOPREIS
ORDER BY STATUS DESC, z.BEZEICHNUNG;

-- 7. Performance-optimierte Version mit EXISTS
SELECT 
    z.ZUTATENNR,
    z.BEZEICHNUNG,
    z.EINHEIT,
    z.BESTAND,
    z.NETTOPREIS,
    ROUND(z.BESTAND * z.NETTOPREIS, 2) as BESTANDSWERT
FROM ZUTAT z
WHERE NOT EXISTS (
    SELECT 1 
    FROM REZEPTZUTAT rz 
    WHERE rz.ZUTATENNR = z.ZUTATENNR
)
ORDER BY BESTANDSWERT DESC;

-- 8. Ungenutzte Zutaten nach Kategorien (falls Allergene als Kategorien betrachtet werden)
SELECT 
    z.ZUTATENNR,
    z.BEZEICHNUNG,
    z.BESTAND,
    z.NETTOPREIS,
    GROUP_CONCAT(DISTINCT a.ALLERGENNAME SEPARATOR ', ') as ALLERGENE
FROM ZUTAT z
LEFT JOIN REZEPTZUTAT rz ON z.ZUTATENNR = rz.ZUTATENNR
LEFT JOIN ZUTATALLERGEN za ON z.ZUTATENNR = za.ZUTATENNR
LEFT JOIN ALLERGEN a ON za.ALLERGENNR = a.ALLERGENNR
WHERE rz.ZUTATENNR IS NULL
GROUP BY z.ZUTATENNR, z.BEZEICHNUNG, z.BESTAND, z.NETTOPREIS
ORDER BY z.BEZEICHNUNG;
