SELECT 
    ek.ERNAEHRUNGSKATEGORIENAME, COUNT(*) AS ANZAHL_REZEPTE
FROM
     REZEPTERNAEHRUNGSKATEGORIE rek
        LEFT JOIN
    ERNAEHRUNGSKATEGORIE ek ON ek.ERNAEHRUNGSKATEGORIENR = rek.ERNAEHRUNGSKATEGORIENR
GROUP BY rek.ERNAEHRUNGSKATEGORIENR; 